[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  # Enable build optimization
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes and server-side rendering
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = [".next/**"]
  node_bundler = "esbuild"
  # Optimize function bundling
  external_node_modules = ["@next/font", "sharp"]
  # Increase build performance
  [functions.build]
    minify = true
