[build]
  command = "npm run build"
  publish = ".next/standalone"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_STANDALONE = "true"
  NODE_VERSION = "18.17.0"

# Handle static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  included_files = [".next/standalone/**", ".next/static/**"]
  node_bundler = "esbuild"
